### ISSUE TITLE
generate_template.py can't determine what version of Crypto.PublicKey.RSA to install

### ISSUE THREAD

**Issue by dgranville** [elik1001/coreos-kubernetes-generator#1]
generate_template.py can't determine what version of Crypto.PublicKey.RSA to install and then fails.  See output below: 

`
# ./generate_template.py
Verifying required python modules
-----------------------------------------------------------
Skipping module: re, already installed
Skipping module: ast, already installed
Skipping module: pwd, already installed
Skipping module: uuid, already installed
Skipping module: crypt, already installed
Skipping module: shutil, already installed
Skipping module: pprint, already installed
Skipping module: getpass, already installed
Skipping module: requests, already installed
Skipping module: subprocess, already installed

-----------------------------------------------------------
You are missing a required Python module: inquirer
Should we try to install the "inquirer" module ?[n] y
Installing missing module: inquirer
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

-----------------------------------------------------------
You are missing a required Python module: Crypto.PublicKey.RSA
Should we try to install the "Crypto.PublicKey.RSA" module ?[n] y
Installing missing module: Crypto.PublicKey.RSA
  Could not find a version that satisfies the requirement Crypto.PublicKey.RSA (from versions: )
No matching distribution found for Crypto.PublicKey.RSA
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "./generate_template.py", line 437, in <module>
    globals()[pkg] = __import__(pkg)
ImportError: No module named Crypto.PublicKey.RSA
`

**Comment by elik1001** [comment]
I am not next to a computer, but you can try running pip install pycrypto.
You should note, that if the Crypto.PublicKey.RSA module is missing non of
your keys will get generated, i.e. nothing will work till this is addressed.
You can just re-run the script once the module is installed.


On Dec 14, 2017 6:00 PM, "Daniel Granville" <notifications@github.com>
wrote:

generate_template.py can't determine what version of Crypto.PublicKey.RSA
to install and then fails. See output below:

`
./generate_template.py Verifying required python modules

Skipping module: re, already installed
Skipping module: ast, already installed
Skipping module: pwd, already installed
Skipping module: uuid, already installed
Skipping module: crypt, already installed
Skipping module: shutil, already installed
Skipping module: pprint, already installed
Skipping module: getpass, already installed
Skipping module: requests, already installed
Skipping module: subprocess, already installed
------------------------------

You are missing a required Python module: inquirer
Should we try to install the "inquirer" module ?[n] y
Installing missing module: inquirer
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
------------------------------

You are missing a required Python module: Crypto.PublicKey.RSA
Should we try to install the "Crypto.PublicKey.RSA" module ?[n] y
Installing missing module: Crypto.PublicKey.RSA
Could not find a version that satisfies the requirement
Crypto.PublicKey.RSA (from versions: )
No matching distribution found for Crypto.PublicKey.RSA
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
File "./generate_template.py", line 437, in
globals()[pkg] = *import*(pkg)
ImportError: No module named Crypto.PublicKey.RSA
`

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elik1001/coreos-kubernetes-generator/issues/1>, or mute
the thread

**Comment by dgranville** [comment]
Running 
```
pip install pycrypto
```
was the workaround I needed.  Thanks!

**Comment by elik1001** [comment]
I will add the module to the verification part.

Note, one of the current bugs discovered by testing, is the alternative ssl
names file being  overwritten with wrong information.

I also hope to full document all functions which currently there is nothing.

On Dec 14, 2017 6:46 PM, "Daniel Granville" <notifications@github.com>
wrote:

Running

pip install pycrypto

was the workaround I needed. Thanks!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/elik1001/coreos-kubernetes-generator/issues/1#issuecomment-351870570>,
or mute the thread

**Comment by elik1001** [comment]
Fixed in latest build  Version 0.2, now committed to master.
